Added ability to customize Identity Provider Name
catnekaise/cognito-idpool-auth pull request #8
Opened 2024-08-07 15:23 UTC by martinssipenko

Added ability to customize Identity Provider Name which is required in case `issuer` claim is customized in GitHub Enterprise Cloud: https://docs.github.com/en/enterprise-cloud@latest/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-issuer-value-for-an-enterprise

I have not tested this, but I suspect it is the reason why after customizing the claim I'm getting:
```sh
An error occurred (NotAuthorizedException) when calling the GetId operation: Invalid login token. Issuer doesn't match providerName
```

2024-08-20 12:18 UTC, martinssipenko commented
@djonser could please take a look at this?

2024-09-02 06:36 UTC, djonser commented
@martinssipenko sorry for a very late reply to this. I have been on vacation where I forced myself to turn off all notifications. I will review this after work today.

2024-09-02 17:25 UTC, djonser requested changes
It look good but we should add validation to that fails on empty strings in `cognito-identity-provider-name`.

Will the value provided provided for GitHub Enterprise be `token.actions.githubusercontent.com/<issuer-name>` ?

2024-09-02 18:14 UTC, martinssipenko commented
Yes, according to GH docs the value would be:

> To security harden their OIDC configuration, enterprise administrators can configure their enterprise to receive tokens from a unique URL at A`https://token.actions.githubusercontent.com/<enterpriseSlug>`, replacing `<enterpriseSlug>` with the slug value of the enterprise.

An alternative approacch to one I proposed could be that action accepts this slug as an input. I guess it would be more user friendly, but would require more logic in the action code to concat the value if its not empty string. Wdyt? Or I can just add validation as per your request.

2024-09-03 07:59 UTC, martinssipenko commented
@djonser Added validation in 86b6cf1, please take a look at let me know if further change is necessary. I have tested my forked version in one of my projects and can confirm it works.

2024-09-03 14:43 UTC, djonser commented
> An alternative approacch to one I proposed could be that action accepts this slug as an input. I guess it would be more user friendly, but would require more logic in the action code to concat the value if its not empty string. Wdyt? Or I can just add validation as per your request.

Its better to have it explicit (as you did in your commit) so that it can work with a changed/added/migrated provider name in the future.

2024-09-03 14:44 UTC, djonser approved these changes

2024-09-03 14:47 UTC, djonser commented
Thanks for the contribution @martinssipenko.

I will sort out moving the v1 tag for this commit a bit little later today (need to refresh my memory).

2024-09-03 14:47 UTC, merged

2024-09-03 14:47 UTC, martinssipenko commented
Great, I would greatly appriciate if this could be merged and released 🙏

2024-09-03 14:58 UTC, martinssipenko commented
You should be able to just create a new `v1.0.2` relase from main branch and that should do the trick.

2024-09-03 16:37 UTC, djonser commented
@martinssipenko There we go. Let me know if you run into any problems.